services:
  auctionhub.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CONTEXT_DATA_SOURCE=${CONTEXT_DATA_SOURCE}
      - LOKI_SERVICE_URL=${LOKI_SERVICE_URL}
      - OPEN_TELEMETRY_URL=${OPEN_TELEMETRY_URL}
    ports:
      - "3000:8080"
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
